### ISSUE TITLE
If only one candle, It does not appear on the canvas

### ISSUE THREAD

**Issue by kit998** [Indemos/Canvas-Desktop#2]
When I test the Canvas program, I set the number of candles to 1, It does not appear on the canvas. At this time, I wheel the mouse, the one candle appears in the canvas. further, if  I set the number of candles to 2, there only one candle appears in the canvas.

**Comment by artemiusgreat** [comment]
@kit998 At the moment I'm working on the cross-platform version of this library, so for now can only suggest a couple of potential fixes. 

**Make sure that method converting chart values to screen pixels doesn't return `NaN` when `MinIndex` is equal to `MaxIndex`**

You may need to replace method [GetPixels](https://github.com/Indemos/Canvas/blob/52f017ceeb9e7b07ef5a06968f732c2ca657646d/ComponentComposer.cs#L383) with this one. 

```C#
public virtual Point GetPixels(ICanvasControl panel, Point input)
{
  // Convert to device pixels

  var deltaX = Equals(MaxIndex, MinIndex) ? 1.0 : (input.X - MinIndex) / (MaxIndex - MinIndex);
  var deltaY = Equals(MaxValue, MinValue) ? 1.0 : (input.Y - MinValue) / (MaxValue - MinValue);
  var deltaW = panel.W;
  var deltaH = panel.H;

  // Percentage to pixels, Y is inverted

  input.X = deltaW * deltaX;
  input.Y = deltaH - deltaH * deltaY;

  return input;
}
```
Then, make sure that [IndexStep](https://github.com/Indemos/Canvas/blob/52f017ceeb9e7b07ef5a06968f732c2ca657646d/ComponentComposer.cs#L45) property doesn't have this issue. 

Then, make sure that [GetEnumerator](https://github.com/Indemos/Canvas/blob/52f017ceeb9e7b07ef5a06968f732c2ca657646d/ComponentComposer.cs#L292) start enumeration from index 0.

**Comment by artemiusgreat** [comment]
I haven't checked the old version of the library, but testing the new cross-platform version I see that all shapes are displayed as they should. 

**Stream**

![image](https://user-images.githubusercontent.com/5140879/163472376-28e642ea-b9d3-43b9-a278-03ae8787460e.png)

**Two points** 

![image](https://user-images.githubusercontent.com/5140879/163472477-6d9efea7-0a40-4241-a70b-451b355a3f68.png)

**One point** 

![image](https://user-images.githubusercontent.com/5140879/163472567-87b9990e-d1e7-4771-9a3b-e38bac409060.png)

In case of one point only candle and bars are displayed because lines and polygons require at least 2 coordinates to form a shape. To reproduce, the existing [sample](https://github.com/Indemos/Canvas-Desktop/blob/main/Samples/Client.WPF/MainWindow.xaml.cs#L53) in this repo was used with small adjustment. 

```
Counter(null, null);  // Draw a single item instead of streaming by timer 

//Clock.Enabled = true;
//Clock.Elapsed += (sender, e) => Dispatcher.Invoke(() => Counter(sender, e));
```
