### ISSUE TITLE
Is it possible to place a big amount of text marks n canvas?

### ISSUE THREAD

**Issue by kv-gits** [Indemos/Canvas-Desktop#3]
Need to mark almost every bar with some char mark.

**Comment by artemiusgreat** [comment]
1. Copy paste one of the shape models, in your case preferably [CandleGroupModel](https://github.com/Indemos/Canvas-Desktop/blob/main/Canvas.Source/Models/Groups/CandleGroupModel.cs#L58) 
2. On the line 58 you can see a definition of the candle shape - a list of 5 `PointModel`s defining vertices that will be connected and will create a candle. Each `PointModel` has X and Y property. Y is vertical position of the shape, X - horizontal. In this model you can see that when X  is 0 this is a horizontal center of the bar, so in order to draw a candle, the variable `size` is used to shift two points 4 pixels to the left from the center, two points to the right of the center. Then `Skia` will connect these points and will convert them into a [shape](https://github.com/Indemos/Canvas-Desktop/blob/main/Canvas.Source/Controls/CanvasPanelControl.cs#L193).
3. Having said that, in your model, instead of defining list of points and calling method [CreateShape](https://github.com/Indemos/Canvas-Desktop/blob/main/Canvas.Source/Controls/CanvasPanelControl.cs#L193) you need to pass only a single `PointModel(0, Y + 50)` to the horizontal center of the bar and 50 pixels above the bar and call method [CreateLabel](https://github.com/Indemos/Canvas-Desktop/blob/main/Canvas.Source/Controls/CanvasPanelControl.cs#L224) to draw text. 

If I have time this weekend, I may create a sample to demonstrate it.

**Comment by artemiusgreat** [comment]
[Done](https://github.com/artemiusgreat/Canvas-Desktop-Label-Shapes/tree/main) 
[Example](https://github.com/artemiusgreat/Canvas-Desktop-Label-Shapes/blob/main/LabelGroupModel.cs) of a custom text shape. 

![image](https://user-images.githubusercontent.com/5140879/162577517-e5a20f1c-4c4b-45a6-bac3-f62538b500ce.png)
